[project]
name = "VXTool"
version = "0.2"
dependencies = [
    "pygame==2.1.2",
]

[tool.setuptools]
packages = ["VXTool", "VXTool_template"]

[tool.ruff]
extend-select = ["I"]
exclude = ["VXTool_template"]
fix = true
